name: protein-conformational-sampling
channels:
  - conda-forge
  - omnia
  - bioconda
dependencies:
  - python=3.7
  - openmm
  - openmmtools
  - mdtraj
  - numpy
  - pandas
  - biopython
  - pdbfixer
  - openmmforcefields